### PR TITLE
Disable search field

### PR DESCRIPTION
**Pull request by error414**
When I used angular-select in mobile, compiled by cca, I had problem with search field, because when i clicked to select, SW keyboard atomaticcaly appeared, because search field got focus. It is quite unusable.

I found one solution "readonly", it works fine for me.

### CODE REVIEW

**Comment by indrimuska** [comment]
Hi @error414, very interesting feature, good job!
At the moment, if the selector already has a value, by focusing on the input field you'll be able to remove that (the last) selected item by hitting <kbd>Backspace</kbd>. What I realized is that this behavior won't be the same if you set the field to a `readonly` state, isn't it?

**Comment by error414** [comment]
Hi,

you are doing greate job :). 

You right, with backspace is problem, backspace can delete value from select but backspace has other unplesant property. If "select" has value and I press backspace so backspace can delete value but moreover backspace invoke action "go back in history". This problem isn't on mobile or chrome app. 

I have to find solution for this. 

BTW: do you have some E2E tests?

**Comment by error414** [comment]
Hi,

I found solution, maybe. Can you check it, please?

**Comment by indrimuska** [comment]
Ok, I created a plunker example with your solution, and it seems to work great with <kbd>Backspace</kbd> button, but it also generates another big problem: when I remove a value form the select, I am not able to type something anymore.

This is the plunker: http://plnkr.co/edit/zpkhbXZHoB7bklCVffxI?p=preview

---

**EDIT:** I don't have E2E test nor any other test, 'cause I don't have the time to create them by myself. It would be very great if you could contribuite to their creation :)

**Comment by error414** [comment]
I am not sure that I know what you mean. Can you create video, or somethink like that? I found one bug but it is on production code too. https://youtu.be/v1x9PUZCQsc

**Comment by indrimuska** [comment]
Check out this GIF image (click on it to view it larger):

ezgif-593614563

**Comment by error414** [comment]
It is exactly what my patch do. Base problem is on mobile devices, if "search's input" get focus so android (I tested it only in android) will open SW keyboard. I know only one solution for this, and it is disable search field. Use SW keyboard on mobile for search in select is unconfortable, because mobile devices have small screen. "disable-search" is only for mobile devices. On PC isn't reason why disable it. "disable search" mean that you cant type anythink to select.

**Comment by indrimuska** [comment]
Ok, now I understand why you've named the feature `disableSearch`!
Well done, let's go for it.
It needs a little update, but don't worry, I'll do it after merging the PR.

**Pull request merged**
