### PR TITLE
Prevents empty selectedValues from raising an error when it shouldn't.

### PR DESCRIPTION
**Pull request by juliomenendez**
Fixes this issue when the selectedValues is empty.

screen shot 2016-08-24 at 11 20 51 am

### CODE REVIEW

**Comment by indrimuska** [comment]
Thank you @juliomenendez for posting this.
Can you please provide a valid example showing how to reproduce this issue?

**Comment by juliomenendez** [comment]
Basically on any selector where the model is null and the field is required.

`select(selector, value-attr='value', model='$ctrl.frequency', placeholder='Frequency...', options='$ctrl.availableFrequencies', require='true')`

Sorry, the example is in `jade/pug`.

**Comment by indrimuska** [comment]
Got it, thanks! I'm going to review it and I'll get back to you.

**Comment by indrimuska** [comment]
Well, it works very well but I can't merge into your branch since the correct fix consists on forcing `selectedValues` to be an array. I'm going to release a new version with the solution for this.

Thank you again for submitting this. 👍

**Comment by indrimuska** [comment]
The fix for this issue has been released in version [1.4.4](https://github.com/indrimuska/angular-selector/releases/tag/1.4.4).

**Comment by juliomenendez** [comment]
Perfect, thank you!

**Pull request closed without merging**
